//
//  ProductsData.swift
//  A2_FA_iOS_eduardo_C0777368
//
//  Created by Eduardo Cardona on 2021-05-21.
//

import Foundation


let prodData:[[String : Any]] = [
    ["provider" : "Sega" , "price" : 50.99, "id" : "SG0001", "name" : "Sega Genesis" , "p_description" : "The Sega Genesis, known as the Mega Drive outside North America, is a 16-bit fourth-generation home video game console developed and sold by Sega. The Genesis was Sega's third console and the successor to the Master System. Sega released it in 1988 in Japan as the Mega Drive, and in 1989 in North America as the Genesis. In 1990, it was distributed as the Mega Drive by Virgin Mastertronic in Europe, Ozisoft in Australasia, and Tec Toy in Brazil. In South Korea, it was distributed by Samsung as the Super Gam*Boy and later the Super Aladdin Boy."],
    ["provider" : "Sega" , "price" : 100.99, "id" : "SG0002", "name" : "Sega Saturn" , "p_description" : "The Sega Saturn is a home video game console developed by Sega and released on November 22, 1994, in Japan, May 11, 1995, in North America, and July 8, 1995, in Europe. Part of the fifth generation of video game consoles, it was the successor to the successful Sega Genesis. The Saturn has a dual-CPU architecture and eight processors. Its games are in CD-ROM format, and its game library contains several ports of arcade games as well as original games."],
    ["provider" : "Sega" , "price" : 130.99, "id" : "SG0003", "name" : "Sega Dreamcast" , "p_description" : "The Dreamcastis a home video game console released by Sega on November 27, 1998, in Japan, September 9, 1999, in North America, and October 14, 1999, in Europe. The Dreamcast was Sega's final home console, marking the end of the company's eighteen years in the console market."],
    ["provider" : "Sony" , "price" : 79.99, "id" : "PS0001", "name" : "Play Station 1" , "p_description" : "The PlayStation (abbreviated as PS, commonly known as the PS1 or its codename PSX) is a home video game console developed and marketed by Sony Computer Entertainment. It was first released on 3 December 1994 in Japan, 9 September 1995 in North America, 29 September 1995 in Europe, and 15 November 1995 in Australia, and was the first of the PlayStation line of video game consoles."],
    ["provider" : "Sony" , "price" : 120.99, "id" : "PS0002", "name" : "Play Station 2" , "p_description" : "The PlayStation 2 (PS2) is a home video game console developed and marketed by Sony Computer Entertainment. It was first released in Japan on March 4, 2000, in North America on October 26, 2000, in Europe on November 24, 2000, and in Australia on November 30, 2000. It is the successor to the original PlayStation, as well as the second installment in the PlayStation console line-up."],
    ["provider" : "Sony" , "price" : 180.99, "id" : "PS0003", "name" : "Play Station 3" , "p_description" : "The PlayStation 3 (PS3) is a home video game console  developed by Sony Computer Entertainment. It is the successor to PlayStation 2, and is part of the PlayStation brand of consoles. It was first released on November 11, 2006 in Japan, November 17, 2006 in North America, and March 23, 2007 in Europe and Australia."],
    ["provider" : "Sony" , "price" : 250.99, "id" : "PS0004", "name" : "Play Station 4" , "p_description" : "The PlayStation 4 (PS4) is a home video game console developed by Sony Computer Entertainment. Announced as the successor to the PlayStation 3 in February 2013, it was launched on November 15, 2013, in North America, November 29, 2013 in Europe, South America and Australia, and on February 22, 2014 in Japan."],
    ["provider" : "Microsoft" , "price" : 95.99, "id" : "XB0001", "name" : "Xbox" , "p_description" : "The Xbox is a home video game console and the first installment in the Xbox series of video game consoles manufactured by Microsoft. It was released as Microsoft's first foray into the gaming console market on November 15, 2001, in North America, followed by Australia, Europe and Japan in 2002. It was also the first major console produced by an American company since the release of the Atari Jaguar in 1993."],
    ["provider" : "Microsoft" , "price" : 160.99, "id" : "XB0002", "name" : "Xbox 360" , "p_description" : "The Xbox 360 is a home video game console developed by Microsoft. As the successor to the original Xbox, it is the second console in the Xbox series. It was officially unveiled on MTV on May 12, 2005, with detailed launch and game information announced later that month at the 2005 Electronic Entertainment Expo"],
    ["provider" : "Microsoft" , "price" : 230.99, "id" : "XB0003", "name" : "Xbox One" , "p_description" : "The Xbox One is a line of home video game consoles developed by Microsoft. Announced in May 2013, it is the successor to Xbox 360 and the third base console in the Xbox series of video game consoles. It was first released in North America, parts of Europe, Australia, and South America in November 2013 and in Japan, China, and other European countries in September 2014. It is the first Xbox game console to be released in China, specifically in the Shanghai Free-Trade Zone. Microsoft marketed the device as an all-in-one entertainment system, hence the name Xbox One."],
    ["provider" : "Nintendo" , "price" : 80.99, "id" : "NI0001", "name" : "Nintendo 64" , "p_description" : "The Nintendo 64 (abbreviated as N64, stylized as NINTENDO64) is a home video game console developed and marketed by Nintendo. It was first released on June 24, 1996 in Japan, September 29, 1996 in North America, and March 1, 1997 in Europe and Australia. It was the last major home console to use cartridges as its primary storage format until the Nintendo Switch in 2017."],
    ["provider" : "Nintendo" , "price" : 110.99, "id" : "NI0002", "name" : "Nintendo Game Cube" , "p_description" : "The Nintendo 64 (abbreviated as N64, stylized as NINTENDO64) is a home video game console developed and marketed by Nintendo. It was first released on June 24, 1996 in Japan, September 29, 1996 in North America, and March 1, 1997 in Europe and Australia. It was the last major home console to use cartridges as its primary storage format until the Nintendo Switch in 2017."],
    ["provider" : "Nintendo" , "price" : 140.99, "id" : "NI0003", "name" : "Nintendo Wii" , "p_description" : "The Wii is a home video game console developed and marketed by Nintendo. It was first released on November 19, 2006 in North America and in December 2006 for most other regions."],
    ["provider" : "Nintendo" , "price" : 150.99, "id" : "NI0004", "name" : "Nintendo Wii U" , "p_description" : "The Wii U is a home video game console developed by Nintendo as the successor to the Wii. Released in late 2012, it is the first eighth-generation video game console."],
    
]

